version: 1
auto-merge-settings:
  merge_level: "patch"
  merge_strategy: "rebase"
  skip_ci: false
  delete_branch: true
  commit_title: Auto-merge dependabot PR
  commit_message: Auto-merge dependabot PR by @dependabot-auto-merge
  skip_check_runs: false
