[package]
name = "chnroutes"
version = "0.1.0"
edition = "2021"

[dependencies]
ipnet = "2.9.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
thiserror = "1.0.61"
enum-tools = "0.5.3"

clap = { version = "4.5.4", features = ["derive"], optional = true }
colored = { version = "2.1.0", optional = true }

[target.'cfg(windows)'.dependencies]
encoding_rs = { version = "0.8.34" }

[features]
build-binary = ["clap", "colored"]

[lib]
name = "chnroutes"
path = "src/lib.rs"

[[bin]]
name = "chnroutes"
path = "src/main.rs"
required-features = ["build-binary"]

[[example]]
name = "basic"
path = "examples/basic.rs"
